MongoDB:
  image: mongo
  volumes:
    - /srv/docker/mongodb:/var/lib/mongodb
  restart: always
Api:
  image: lukaszpyrzyk/tankindungeonapi
  ports:
    - 8080:8080
  command: "-mongohost=MongoDB"
  links:
    - MongoDB
  restart: always
